---
title: "Part 8: 3D Plotly Scatter"
author: "Tyler Faits"
date: "12/21/2020"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
setwd("/Users/labadmin2/Documents/infant_gill/ProperLabels")
require(ggplot2)
require(ComplexHeatmap)
require(reshape2)
library(RColorBrewer)
require(DESeq2)
require(gridExtra)
require(Rmisc)
require(vegan)
require(circlize)
#require(hclust)
require(NbClust)
#Create color palette to be used for plotting
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

#Load the count matrixes for phylum, genus, and species
phyla <- readRDS("RefSeq2_p.RDS")
genus <- readRDS("RefSeq2_g.RDS")
species <- readRDS("RefSeq2_s.RDS")

#delta/epsilon subdivisions is a part of Proteobacteria, so we're going with that.
phyla["Proteobacteria",] <- phyla["Proteobacteria",] + phyla["delta/epsilon subdivisions",]
phyla <- phyla[rownames(phyla) != "delta/epsilon subdivisions",]
#Require more than 1000 reads in a sample to be analyzed
phyla <- phyla[,apply(phyla,2,sum)>10000]
phyla <- phyla[apply(phyla,1,sum) > 10,]
genus <- genus[,apply(genus,2,sum)>10000]
genus <- genus[apply(genus,1,sum) > 10,]
species <- species[,apply(species,2,sum)>10000]
species <- species[apply(species,1,sum) > 10,]
colnames(genus) <- gsub("S|S0","X",colnames(genus))
colnames(phyla) <- gsub("S|S0","X",colnames(phyla))
colnames(species) <- gsub("S|S0","X",colnames(species))
colnames(genus)[grep("DNA",colnames(genus))] <- c("DNA1","DNA2","DNA3","DNA4","DNA5")
colnames(phyla)[grep("DNA",colnames(phyla))] <- c("DNA1","DNA2","DNA3","DNA4","DNA5")
colnames(species)[grep("DNA",colnames(species))] <- c("DNA1","DNA2","DNA3","DNA4","DNA5")
#Create a counts-per-million matrix for each taxonomic level
CPMphyla <- t(t(phyla)/apply(phyla,2,sum)*1000000)
CPMgenus <- t(t(genus)/apply(genus,2,sum)*1000000)
CPMspecies <- t(t(species)/apply(species,2,sum)*1000000)
map <- readRDS("../InfantMappingData2.RDS")
map$PrePostSympt[is.na(map$PrePostSympt)] <- "none"
map$PrePostSympt[map$PrePostSympt=="none"] <- "Healthy"
map$PrePostSympt[map$Symptoms=="Yes" & !is.na(map$Symptoms)] <- "Active"
map <- map[colnames(genus),]

fullGenus <- readRDS("ggGenusWithClusters.RDS")

BetaDivMap <- vegdist(t(CPMgenus[,map$Sample[map$MothChild=="Infant" & map$Sample %in% colnames(CPMgenus) & map$Age < 1000]]), method="bray")
healthyBetaDivMap <- vegdist(t(CPMgenus[,map$Sample[map$MothChild=="Infant" & map$Sample %in% colnames(CPMgenus) & map$Age < 1000 & map$InfectionStatus=="Healthy"]]), method="bray")
sickBetaDivMap <- vegdist(t(CPMgenus[,map$Sample[map$MothChild=="Infant" & map$Sample %in% colnames(CPMgenus) & map$Age < 1000 & map$InfectionStatus=="RespiratoryIllness"]]), method="bray")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
set.seed(5)
capture.output(preNMDS <- metaMDS(t(CPMgenus[apply(CPMgenus[,map$Sample[map$Age<1000]],1,sum)>0,map$Sample[map$Age<1000]]), distance="bray", k=3,try=10, trymax=500,autotransform = FALSE))

fullGenus$namedCluster6 <- fullGenus$Cluster6
fullGenus$namedCluster6[fullGenus$namedCluster6=="1"] <- "Haemophilus"
fullGenus$namedCluster6[fullGenus$namedCluster6=="2"] <- "Moraxella"
fullGenus$namedCluster6[fullGenus$namedCluster6=="3"] <- "Dolosigranulum"
fullGenus$namedCluster6[fullGenus$namedCluster6=="4"] <- "Anaerobacillus"
fullGenus$namedCluster6[fullGenus$namedCluster6=="5"] <- "Streptococcus"
fullGenus$namedCluster6[fullGenus$namedCluster6=="6"] <- "Staphylococcus"
fullGenus$colors6 <- "#000000"
fullGenus$colors6[fullGenus$namedCluster6=="Haemophilus"] <- col_vector[13]
fullGenus$colors6[fullGenus$namedCluster6=="Moraxella"] <- col_vector[14]
fullGenus$colors6[fullGenus$namedCluster6=="Dolosigranulum"] <- col_vector[12]
fullGenus$colors6[fullGenus$namedCluster6=="Anaerobacillus"] <- col_vector[9]
fullGenus$colors6[fullGenus$namedCluster6=="Streptococcus"] <- col_vector[18]
fullGenus$colors6[fullGenus$namedCluster6=="Staphylococcus"] <- col_vector[17]


DrawInfo <- data.frame(sampNames=map$Sample[map$Age<1000],
                      Colors=unlist(lapply(map$Sample[map$Age<1000],function(x){fullGenus$colors6[fullGenus$Sample==x & fullGenus$Genus=="Staphylococcus"]})),
                      Groups=unlist(lapply(map$Sample[map$Age<1000],function(x){fullGenus$namedCluster6[fullGenus$Sample==x & fullGenus$Genus=="Staphylococcus"]})),stringsAsFactors = FALSE)

taxInfo <- data.frame(Age=map[map$Age<1000,"Age"],
                      Sick=rep(0,sum(map$Age<1000)),
                      Healthy=rep(0,sum(map$Age<1000)),
#                      Antibiotic=rep(0,sum(map$Age<1000)),
                      # Staphylococcus=CPMgenus["Staphylococcus",map$Sample[map$Age<1000]],
                      # Streptococcus=CPMgenus["Streptococcus",map$Sample[map$Age<1000]],
                      # Haemophilus=CPMgenus["Haemophilus",map$Sample[map$Age<1000]],
                      # Anaerobacillus=CPMgenus["Anaerobacillus",map$Sample[map$Age<1000]],
                      # Moraxella=CPMgenus["Moraxella",map$Sample[map$Age<1000]],
                      # Dolosigranulum=CPMgenus["Dolosigranulum",map$Sample[map$Age<1000]],
                      stringsAsFactors = FALSE)
rownames(taxInfo) <- map$Sample[map$Age<1000]
taxInfo[map[rownames(taxInfo),"InfectionStatus"] == "RespiratoryIllness","Sick"] <- 1
taxInfo[map[rownames(taxInfo),"InfectionStatus"] == "Healthy","Healthy"] <- 1
#taxInfo[map[rownames(taxInfo),"PrePostSympt"] == "Post","Antibiotic"] <- 1

require(plotly)
myNMDS <- as.data.frame(scores(preNMDS,"sites"))
myNMDS$Colors <- DrawInfo$Colors
myNMDS$Groups <- DrawInfo$Groups
myNMDS$PrePostSympt <- "FAILED"
for(sampName in rownames(myNMDS)){
  myNMDS[sampName,"PrePostSympt"] <- map[sampName,"PrePostSympt"]
}
```

```{r, echo=FALSE, warning=FALSE,}
ef <- envfit(preNMDS, choices=c(1,2,3), taxInfo, permu=999)
plot_ly(x=myNMDS$NMDS1, y=myNMDS$NMDS2, z=myNMDS$NMDS3,
        type="scatter3d",mode="markers",
        color=DrawInfo$Groups, colors=col_vector[c(28,12,13,14,17,18)]) %>%
  add_trace(x=c(0,ef$vectors$arrows[1,1]),y=c(0,ef$vectors$arrows[1,2]),z=c(0,ef$vectors$arrows[1,3]),
            type = "scatter3d",mode="lines",name="Age",
            line=list(color="black", width=6),
            inherit=FALSE) %>%
  add_trace(x=c(0,ef$vectors$arrows[2,1]),y=c(0,ef$vectors$arrows[2,2]),z=c(0,ef$vectors$arrows[2,3]),
            type = "scatter3d",mode="lines",name="LRTI",
            line=list(color="red", width=6),
            inherit=FALSE) %>%
  add_trace(x=c(0,ef$vectors$arrows[3,1]),y=c(0,ef$vectors$arrows[3,2]),z=c(0,ef$vectors$arrows[3,3]),
            type = "scatter3d",mode="lines",name="Healthy",
            line=list(color="cyan", width=6),
            inherit=FALSE)
```
